theme: jekyll-theme-minimal
title: MoveMouse
logo: /assets/images/logo.png
description: MoveMouse A MacOS Application that moves the mouse
show_downloads: true
teaser: /assets/images/logo.png
classes: wide


author:
  name     : "Alejandro Cordón Ureña"
  avatar   : "/assets/images/logo.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Madrid, Spain"